### PR TITLE
Add ability to filter by columns for charts

### PR DESCRIPTION
**Pull request by spinscale**
This allows to specify CSV files with more columns, in case you only want to display a few of them (or split them into several charts).

### CODE REVIEW

**Comment by MykolaGolubyev** [comment]
Will try to take a look tonight! Thanks for creating a PR!
Do you mind sharing where/how you use znai? Here is a good place to provide this info: https://github.com/testingisdocumenting/znai/discussions/824

**Comment by MykolaGolubyev** [comment]
Any chance you can also update documentation?

**Comment by spinscale** [comment]
regarding usage: just my personal knowledge sharing/todo management tool for now. Dealing with source code plus annotations/comments looks much better than many other solutions, when you want share content with others. Maybe I'll try to introduce it for further knowledge sharing/internal documentation soon.

Will take a look at the docs.

**Comment by MykolaGolubyev** [comment]
Nice! Code looks good! 
Would it make sense to validate that columns provided are not misprinted or still present in the data set?

**Comment by spinscale** [comment]
Thx for taking a look!

Are you referring to a check that ensures that only existing column names are selected and otherwise an exception is thrown or did I misunderstand you?

**Comment by MykolaGolubyev** [comment]
Yes, if data set has A, B, and C columns but a user specifies "A1" I think it would be nice to fail the docs build process.

**Comment by spinscale** [comment]
Added a check as well as a test

**Comment by MykolaGolubyev** [comment]
Could I ask you to add a last thing? It is OK to say no and I add it in a separate PR.
a release notes related file like here: https://github.com/testingisdocumenting/znai/pull/1156/files#diff-eea3a9673bb6ea6dc6472f787b443e912168df50e374b70308c34c029563b86c

totally forgot to mention at the beginning.
Clearly need a better onboarding.

**Comment by spinscale** [comment]
done. Also, just push on this branch for any change if it simplifies merging on your side.

**Review by MykolaGolubyev — APPROVED** [review]

**Comment by MykolaGolubyev** [comment]
@spinscale got distracted here. Are you waiting for the release of this PR or are you able to use the code changes in your project?

**Comment by spinscale** [comment]
thanks for getting back. All good if you just put it in the next release for the coming days/weeks, no need to rush anything out.

Hope you have some kind of holidays!

**Comment by MykolaGolubyev** [comment]
@spinscale Happy New Year! 
this feature was released

**Pull request merged**
