### PR TITLE
fix: include subheadings in znai index

### PR DESCRIPTION
**Pull request by evinaik**
See #589

### CODE REVIEW

**Comment by MykolaGolubyev** [comment]
nice! thank you.
when you merge this PR, could you please use `search: <...>` as a final commit message

**Review by MykolaGolubyev — APPROVED** [review]

**Comment by evinaik** [comment]
will do!

**Comment by MykolaGolubyev** [comment]
just in case for future, you don't have to force re-push to change message. At the end you can pick `squash and merge` and it will use this PR message which you can edit.

**Comment by evinaik** [comment]
> just in case for future, you don't have to force re-push to change message. At the end you can pick `squash and merge` and it will use this PR message which you can edit.

interesting, had no idea — thanks for the tip!

**Comment by evinaik** [comment]
Does the build step generally take this long?

**Comment by MykolaGolubyev** [comment]
it shouldn't. Looking.

**Comment by MykolaGolubyev** [comment]
Looks like current build action workflow is not taking fork PR based trigger. There is no build associated with this PR
I just created PR to enable it for PR and not just branches: https://github.com/testingisdocumenting/znai/pull/595

**Comment by MykolaGolubyev** [comment]
Please pull in new changes from master, to pull in changes to GitHub actions

**Pull request merged**
